import yt_dlp


# ============================================
# YOUTUBE SEARCH LAYER
# ============================================
#
# Responsibility:
#     This module performs YouTube search using
#     yt-dlp and returns ranked candidate songs.
#
# This module DOES:
#     - search YouTube
#     - extract metadata
#     - filter invalid results
#     - return ranked candidates
#
# This module DOES NOT:
#     - download audio
#     - play music
#     - perform AI semantic analysis
#     - control playlist state
#
# Design Principle:
#     Keep the search layer independent from
#     playback, playlist, and hardware logic.
#
# ============================================


def search(query):

    """
    Search YouTube using a semantic query.

    Input:
        query:
            A cleaned search string generated by
            the command parser or AI semantic layer.

    Output:
        A list of ranked song candidates:

            [
                (url, title),
                ...
            ]

    Example:
        search("Taylor Swift")

        returns:

            [
                (
                    "https://youtube.com/...",
                    "Taylor Swift - ..."
                ),
                ...
            ]

    Design Notes:
        This layer only retrieves candidates.
        The main state machine decides which
        candidate to play.
    """

    print("\nSearching YouTube...")

    # ====================================
    # YT-DLP SEARCH CONFIGURATION
    # ====================================
    #
    # This configuration performs metadata
    # search only. No audio file is downloaded
    # in this stage.
    #
    # Search behavior:
    #     ytsearch10
    #         Retrieve top 5 candidates.
    #
    #     skip_download=True
    #         Metadata only.
    #
    #     noplaylist=True
    #         Avoid playlist extraction.
    #
    # ====================================

    ydl_opts = {

        "default_search": "ytsearch5",

        "quiet": True,

        "skip_download": True,

        "noplaylist": True
    }

    try:

        # ====================================
        # EXECUTE SEARCH
        # ====================================
        #
        # yt-dlp returns raw metadata for
        # multiple search candidates.
        #
        # The result may contain invalid or
        # incomplete entries, so validation is
        # required before returning data to the
        # main system.
        #
        # ====================================

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:

            info = ydl.extract_info(

                query,

                download=False
            )

        # ====================================
        # EXTRACT SEARCH RESULTS
        # ====================================
        #
        # Use .get() instead of direct indexing
        # to avoid crashing if yt-dlp returns
        # an unexpected structure.
        #
        # ====================================

        entries = info.get("entries", [])

        results = []

        # ====================================
        # VALIDATE AND NORMALIZE CANDIDATES
        # ====================================
        #
        # Only the minimum metadata required by
        # downstream modules is extracted:
        #
        #     - webpage_url
        #     - title
        #
        # Candidate format:
        #
        #     (
        #         url,
        #         title
        #     )
        #
        # This keeps the interface simple and
        # reduces coupling with yt-dlp internals.
        #
        # Filter invalid search results.
        #
        # Only candidates containing both
        # title and webpage URL are preserved.
        #
        # Convert raw yt-dlp entries into a
        # simplified candidate representation:
        #
        #     (url, title)
        #
        # This normalized format is consumed
        # by the playback state machine.
        # ====================================

        for entry in entries:

            if not entry:

                continue

            title = entry.get("title")

            url = entry.get("webpage_url")

            if not title or not url:

                continue

            results.append(

                (url, title)
            )

        # ====================================
        # RETURN RANKED CANDIDATES
        # ====================================
        #
        # Results preserve yt-dlp ranking order.
        #
        # The main state machine consumes this
        # list for:
        #
        #     - first song playback
        #     - search-mode next song
        #
        # ====================================

        print(f"\nFound {len(results)} results")

        return results

    except Exception as e:

        # ====================================
        # GRACEFUL FAILURE
        # ====================================
        #
        # Search failure should not terminate
        # the whole voice music system.
        #
        # Return an empty list so the main loop
        # can recover and request another input.
        #
        # ====================================

        print("\nYouTube search failed")

        print(e)

        return []