import json


# ============================================
# AI QUERY BUILDER
# ============================================
#
# Responsibility:
#
#     Convert AI semantic parsing results
#     into optimized YouTube search queries.
#
# This module DOES:
#
#     - clean AI-generated JSON output
#     - parse semantic entities
#     - select stable search keywords
#     - build search queries
#
# This module DOES NOT:
#
#     - perform AI inference
#     - search YouTube
#     - download music
#     - play audio
#
# Design Flow:
#
#     User Request
#             ↓
#       AI Semantic Layer
#             ↓
#        Query Builder
#             ↓
#      YouTube Search
#
# Design Principle:
#
#     Separate semantic understanding
#     from search optimization.
#
# ============================================


# ============================================
# BUILD SEARCH QUERY
# ============================================

def build_query(ai_result):

    """
    Build a simplified YouTube search query
    from AI semantic parsing results.

    Input:

        ai_result:
            JSON string generated by
            the AI semantic parser.

    Output:

        Optimized YouTube query string.

    Example:

        Input:

            {
                "artist":"Taylor Swift",
                "song":"Love Story",
                "mood":"romantic"
            }

        Output:

            "Taylor Swift Love Story"

    Design Notes:

        The AI layer extracts meaning.

        This module transforms semantic
        entities into stable search terms.
    """

    # ====================================
    # REMOVE MARKDOWN WRAPPER
    # ====================================
    #
    # AI responses may include markdown
    # code fences such as:
    #
    #     ```json
    #     {...}
    #     ```
    #
    # Remove these wrappers before
    # JSON parsing.
    #
    # ====================================

    ai_result = ai_result.replace(

        "```json",

        ""

    )

    ai_result = ai_result.replace(

        "```",

        ""

    )

    ai_result = ai_result.strip()

    # ====================================
    # JSON STRING → PYTHON DICTIONARY
    # ====================================
    #
    # Convert the cleaned JSON string
    # into a Python dictionary for
    # semantic extraction.
    #
    # ====================================

    data = json.loads(ai_result)

    parts = []

    # ====================================
    # CORE SEARCH ENTITIES ONLY
    # ====================================
    #
    # Preserve only stable entities that
    # improve YouTube search quality.
    #
    # Included:
    #
    #     artist
    #     song
    #     movie
    #     event
    #     year
    #
    # Excluded:
    #
    #     mood
    #     emotional descriptions
    #     long semantic phrases
    #
    # because they often reduce search
    # precision and consistency.
    #
    # ====================================

    if data.get("artist"):

        parts.append(

            str(data["artist"])

        )

    if data.get("song"):

        parts.append(

            str(data["song"])

        )

    if data.get("movie"):

        parts.append(

            str(data["movie"])

        )

    if data.get("event"):

        parts.append(

            str(data["event"])

        )

    if data.get("year"):

        parts.append(

            str(data["year"])

        )

    # ====================================
    # FINAL SEARCH QUERY
    # ====================================
    #
    # Combine selected entities into a
    # compact search query suitable for
    # downstream YouTube retrieval.
    #
    # Example:
    #
    #     Taylor Swift
    #     Love Story
    #     2008
    #
    #             ↓
    #
    #     "Taylor Swift Love Story 2008"
    #
    # ====================================

    return " ".join(parts)